luxmed.username=
luxmed.password=
gmail.app.password=
gmail.app.mail=

# loop repeat intervals and waiting time
loop.retry.max = 5000
loop.retry.interval.minutes = 3
noemail.sleep.interval = 15

### Configuration ###
### turn this proxy to true if you are behind a proxy which blocks playwright to be downloaded,
### then you can download chromedriver manually from here https://developer.chrome.com/docs/chromedriver/downloads
### and provide a path to chrome.exe
is.proxy = true
### path with backspashes, or double slashes
browser.chrome.path = C:/zaibatsu/playground/luxmed-playwright/browser/chrome-win2/chrome.exe
browser.headless = false