luxmed.username=
luxmed.password=

### Configuration ###
### turn this proxy to true if you are behind a proxy which blocks playwright to be downloaded,
### then chrome path will be used a chrome source instead of downloading it automatically.
is.proxy = true
#browser.chrome.path = src\main\resources\browser\chrome-win2\chrome.exe
browser.chrome.path = C:\zaibatsu\playground\luxmed-playwright\browser\chrome-win2\chrome.exe